language: java
sudo: false
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: "$HEROKU_API_KEY"
  app: easy-buying
script:
  - mvn test
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: VqhD7ZojdFsmKRqc68IOUmXwxLiaBqg+EEDbl0TDMuXyxOpY+/taCPiWIQi9hgT6IGsdEGKibfnLfadxzGBtq7EL9l4VdqET+0JW/mUd2Uq2uvesDjCihJ9SwJ7/q0hdi02K9v/Qd5QFT7yhN3q6kw2+wsqhlFiGjIQifNwIKjsl8MhvMoXWhxjxiJS4c7czyOZpt3m66YeCEYjcJLpfGACnJC67N48tgb9W/mu7b2D+UgREU+wsMIDT9FfdrDck4F9gmt9basCfItxoZ4/HsBXgM37rpFfOMRNtn2RCxoi0+oDOFeu6eUSiAYsTbwtx2qCCdPk12XgXFwSS6in0j5E41sLRgyWgfVgPo5ev01ccU9WqBhnQtc76tIK9I3V7+ggfGu0+IUiJAQwTBCzVMuuOuNBk72/LtogDqMmar9CI0jTkES9TECU1GFcrfaa+H19gOoPzcMmy9MDJH/4XHtG55yDjZKpz7khKvxZDYoKk8DklEbUfZLHWO+Ff0k55HHBMT/B7Pqr3W88wNhkP/A2/shI6DCkwspgdO2Iq/Q8OMhpZnZV/pfBl2wWMomO+StfQts+TtvbMF6w4DIdJK2UgXnYb/ckvJki0iA8BPhwETULpooFgoN+SrbOkIxlGLyhMJM/1hqNW9gDSvS64tNWFaKQPEMnq4Ay5WHVIzDs=
