# LOGGING
logging:
  file: build/easy-buying.log
  level:
    org.wpattern.easy.buying: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easy-buying
    username: postgres
    password: vini2808
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# SECURITY
security:
  password:
    secret: secret

# LIQUIBASE
liquibase:
  enabled: true
  change-log: classpath:data/config/master.xml
  url: jdbc:postgresql://localhost:5432/easy-buying
  user: postgres
  password: vini2808
