# APPLICATION
spring:
  application:
    name: Easy Buying
    description: Projeto desenvolvido pelos alunos da Faculdade UNA de Uberlândia, sob orientação do professor @bbranquinho.
    version: @project.version@
  profiles:
    active: dev

# SERVER
server:
  contextPath: /
  port: 9090
